// Project Makoto
// Copyright (C) 2023  Fortunevale
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY
namespace ProjectMakoto.Plugins.Translation.Entities;
#pragma warning disable CS8981
#pragma warning disable CS8618
#pragma warning disable IDE1006
public class Translations : ITranslations
{
    public Dictionary<string, int> Progress = new();
    public CommandTranslation[] CommandList { get; set; }
    #region AutoGenerated
    public commands Commands;
    public sealed class commands
    {
        public translateMessage TranslateMessage;
        public sealed class translateMessage
        {
            public SingleTranslationKey Translated;
            public MultiTranslationKey Queue;
            public SingleTranslationKey Translating;
            public SingleTranslationKey SelectTargetDropdown;
            public SingleTranslationKey SelectTarget;
            public SingleTranslationKey SelectSourceDropdown;
            public SingleTranslationKey SelectSource;
            public SingleTranslationKey SelectProvider;
            public SingleTranslationKey NoContent;
        }
    }
    #endregion AutoGenerated
}